# Generated by Django 5.2.6 on 2025-10-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(unique=True)),
                ('semester_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['semester_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('subject_name', models.CharField(max_length=120)),
                ('course_type', models.CharField(choices=[('MAJOR', 'Major Course'), ('MINOR', 'Minor Course'), ('MD1', 'Major Discipline 1'), ('MD2', 'Major Discipline 2'), ('SKILL', 'Skill Enhancement'), ('VAC1', 'Value Added Course 1'), ('VAC2', 'Value Added Course 2'), ('AEC', 'Ability Enhancement Course'), ('MAJOR1', 'Major 1'), ('MAJOR2', 'Major 2'), ('MAJOR3', 'Major 3'), ('MAJOR4', 'Major 4')], max_length=20)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['course_type', 'subject_name'],
            },
        ),
    ]
