# Generated by Django 5.2.6 on 2025-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcorner', '0002_student_studentsemester_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_type',
            field=models.CharField(choices=[('MAJOR', 'Major Course'), ('MINOR', 'Minor Course'), ('MD1', 'Multidisciplinary 1'), ('MD2', 'Multidisciplinary 2'), ('SKILL', 'Skill Enhancement'), ('VAC1', 'Value Added Course 1'), ('VAC2', 'Value Added Course 2'), ('AEC', 'Ability Enhancement Course')], max_length=20),
        ),
    ]
