# Generated by Django 5.2.6 on 2025-10-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcorner', '0003_alter_subject_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemester',
            name='major_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_enrollments', to='studentcorner.subject'),
        ),
    ]
