# Generated by Django 5.2.6 on 2025-10-02 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcorner', '0004_studentsemester_major_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='class_roll_no',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='session',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
