# Generated by Django 5.2.6 on 2025-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcorner', '0005_remove_certificate_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hard_copy_collected_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hard_copy_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hard_copy_issued',
            field=models.BooleanField(default=False),
        ),
    ]
