# Generated by Django 5.2.6 on 2025-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcorner', '0006_certificate_cgpa_certificate_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='u_registration_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
